# -*- coding: utf-8 -*-
"""PaperMd Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAh-BjzS0RTTE1kF7Bv_9cwfVaie_BeL
"""

!pip install ultralytics -q

from google.colab import drive
drive.mount('/content/drive')

import subprocess
subprocess.run(['pip', 'install', 'ultralytics', '-q'], check=True)

import os, json, re, shutil
from pathlib import Path
from collections import defaultdict, Counter
from urllib.parse import urlparse, unquote, parse_qs
from datetime import datetime
from ultralytics import YOLO

DATASET_ROOT = '/content/drive/MyDrive/dataset'
JSON_DIR     = f'{DATASET_ROOT}/labels'
LABELS_DIR   = f'{DATASET_ROOT}/labels'
IMAGES_DIR   = f'{DATASET_ROOT}/images/training'
DATA_YAML    = f'{DATASET_ROOT}/data.yaml'
PROJECT_DIR  = '/content/runs/detect'
RUN_NAME     = 'papermd_train'
MODELS_DIR   = f'{DATASET_ROOT}/models'

CLASS_MAP = {
    'Figure_Sketch':     0,
    'Text':              1,
    'Link':              2,
    'Table':             3,
    'Formula':           4,
    'Callout':           5,
    'List_Item':         6,
    'Strikeout':         7,
    'Figure_Graph':      8,
    'Figure_Image':      9,
    'Figure_Doodle':     10,
    'Figure_Electrical': 11,
    'Figure_Flowchart':  12,
    'Chemical_Formula':  13,
}

def extract_stem(image_path: str) -> str:
    """Handle all Label Studio path formats → clean filename stem."""
    decoded = unquote(image_path)
    if '/data/local-files/' in decoded:
        qs = parse_qs(urlparse(decoded).query).get('d', [])
        if qs:
            decoded = qs[0]
    if '/data/upload/' in decoded:
        name = re.sub(r'^[0-9a-f]{8}-', '', Path(decoded).name)
        return Path(name).stem
    return Path(decoded).stem

def box_count(f: Path) -> int:
    try:
        data = json.loads(f.read_text())
        return sum(1 for r in data.get('result', []) if r.get('value', {}).get('rectanglelabels'))
    except:
        return 0

def write_data_yaml():
    names = '\n'.join(f'  {i}: {n}' for n, i in sorted(CLASS_MAP.items(), key=lambda x: x[1]))
    content = (
        f"path: {DATASET_ROOT}\n"
        f"train: images/training\n"
        f"val: images/training\n\n"
        f"nc: {len(CLASS_MAP)}\n"
        f"names:\n{names}\n"
    )
    with open(DATA_YAML, 'w') as f:
        f.write(content)
    print("✓ data.yaml written")

print("=" * 55)
print("STEP 1 — Deduplicating JSON annotations")
print("=" * 55)

stem_to_files: dict[str, list[Path]] = defaultdict(list)

for f in Path(JSON_DIR).iterdir():
    if not f.is_file():
        continue
    try:
        data       = json.loads(f.read_text())
        image_path = data.get('task', {}).get('data', {}).get('image', '')
        if image_path:
            stem_to_files[extract_stem(image_path)].append(f)
    except Exception as e:
        print(f"  ✗ {f.name}: {e}")

unique      = {s: fs for s, fs in stem_to_files.items() if len(fs) == 1}
dupes       = {s: fs for s, fs in stem_to_files.items() if len(fs) > 1}
dupe_files  = sum(len(fs) for fs in dupes.values())
wasted      = dupe_files - len(dupes)

print(f"Total JSON files : {sum(len(fs) for fs in stem_to_files.values())}")
print(f"Unique images    : {len(unique)}")
print(f"Duplicate images : {len(dupes)} repeated across {dupe_files} files")
print(f"Files to delete  : {wasted}")

deleted = 0
if dupes:
    print(f"\nDuplicates found:")
    for stem, files in sorted(dupes.items(), key=lambda x: -len(x[1])):
        print(f"\n  {stem}  ({len(files)}x)")
        files_by_boxes = sorted(files, key=box_count, reverse=True)
        keep   = files_by_boxes[0]
        delete = files_by_boxes[1:]
        print(f"    keeping  → {keep.name} ({box_count(keep)} boxes)")
        for f in delete:
            print(f"    deleting → {f.name}")
            f.unlink()
            deleted += 1
    print(f"\n✓ Deleted {deleted} duplicate files. {len(unique) + len(dupes)} unique images remain.")
else:
    print("\n✓ No duplicates found.")


print("\n" + "=" * 55)
print("STEP 2 — Converting annotations to YOLO format")
print("=" * 55)

# Clear existing .txt files
for txt in Path(LABELS_DIR).glob('*.txt'):
    txt.unlink()
os.makedirs(LABELS_DIR, exist_ok=True)

files    = [f for f in os.listdir(JSON_DIR) if os.path.isfile(os.path.join(JSON_DIR, f)) and not f.endswith('.txt')]
skipped  = 0
errors   = 0
best: dict[str, tuple[list[str], int]] = {}
upload_stems: set[str] = set()

print(f"Found {len(files)} annotation files. Converting...\n")

for file_name in files:
    try:
        data       = json.loads(Path(os.path.join(JSON_DIR, file_name)).read_text())
        image_path = data.get('task', {}).get('data', {}).get('image', '')
        if not image_path:
            skipped += 1
            continue

        stem  = extract_stem(image_path)
        lines = []

        if '/data/upload/' in image_path:
            upload_stems.add(stem)

        for res in data.get('result', []):
            val   = res.get('value', {})
            label = (val.get('rectanglelabels') or [''])[0]
            if label not in CLASS_MAP:
                continue

            w = val['width']  / 100
            h = val['height'] / 100
            x = max(0.0, min(1.0, val['x'] / 100 + w / 2))
            y = max(0.0, min(1.0, val['y'] / 100 + h / 2))
            w = max(0.0, min(1.0, w))
            h = max(0.0, min(1.0, h))
            lines.append(f"{CLASS_MAP[label]} {x:.6f} {y:.6f} {w:.6f} {h:.6f}")

        if not lines:
            skipped += 1
            continue

        if len(lines) > best.get(stem, ([], -1))[1]:
            best[stem] = (lines, len(lines))

    except Exception as e:
        errors += 1
        print(f"  ✗ {file_name}: {e}")

for stem, (lines, _) in best.items():
    Path(os.path.join(LABELS_DIR, stem + '.txt')).write_text('\n'.join(lines))

print(f"Converted: {len(best)} | Skipped: {skipped} | Errors: {errors}")

if upload_stems:
    print(f"\n⚠ {len(upload_stems)} images were Label Studio uploads — ensure they are in images/training:")
    for s in sorted(upload_stems):
        print(f"    {s}")

# Validate image ↔ label pairs

print("\n" + "=" * 55)
print("STEP 3 — Validating image/label pairs")
print("=" * 55)

image_stems = {p.stem for p in Path(IMAGES_DIR).glob('*') if p.suffix.lower() in {'.jpg', '.jpeg', '.png'}}
label_stems = {p.stem for p in Path(LABELS_DIR).glob('*.txt')}
matched     = image_stems & label_stems
imgs_only   = image_stems - label_stems
lbls_only   = label_stems - image_stems

print(f"Matched            : {len(matched)}")
print(f"Unannotated images : {len(imgs_only)}")
if lbls_only:
    print(f"Labels w/o image   : {len(lbls_only)}  ← copy these images to images/training")
    for s in sorted(lbls_only):
        print(f"    {s}")

class_names = {v: k for k, v in CLASS_MAP.items()}
counts: Counter = Counter()
for txt in Path(LABELS_DIR).glob('*.txt'):
    for line in txt.read_text().splitlines():
        parts = line.strip().split()
        if parts and parts[0].isdigit():
            counts[int(parts[0])] += 1

print("\nClass distribution:")
for cid in sorted(class_names):
    bar = '█' * (counts[cid] // 2)
    print(f"  {class_names[cid]:<20} {counts[cid]:>4}  {bar}")

# Write data.yaml

print("\n" + "=" * 55)
print("STEP 4 — Writing data.yaml")
print("=" * 55)

write_data_yaml()

# Train

print("\n" + "=" * 55)
print("STEP 5 — Training")
print("=" * 55)

if len(matched) == 0:
    raise RuntimeError("✗ No matched image/label pairs — fix pairing before training.")

print(f"Training on {len(matched)} images...")
model   = YOLO('yolo11n.pt')
results = model.train(
    data     = DATA_YAML,
    epochs   = 100,
    imgsz    = 1280,
    batch    = 8,
    augment  = True,
    project  = PROJECT_DIR,
    name     = RUN_NAME,
    exist_ok = True,
    patience = 20,
)
print(f"\nBest mAP50: {results.results_dict.get('metrics/mAP50(B)', 'N/A'):.4f}")

# Export & save to Drive

print("\n" + "=" * 55)
print("STEP 6 — Exporting & saving weights")
print("=" * 55)

os.makedirs(MODELS_DIR, exist_ok=True)
pt_source = f'{PROJECT_DIR}/{RUN_NAME}/weights/best.pt'

if not os.path.exists(pt_source):
    print(f"✗ Weights not found at {pt_source}")
else:
    timestamp = datetime.now().strftime("%m%d_%H%M")
    img_count = len(list(Path(LABELS_DIR).glob('*.txt')))
    release   = f"{timestamp}_n{img_count}"

    shutil.copy(pt_source, f'{MODELS_DIR}/{release}.pt')
    print(f"✓ .pt   → {MODELS_DIR}/{release}.pt")

    YOLO(pt_source).export(format='onnx', imgsz=1280, simplify=True, opset=12)

    onnx_source = pt_source.replace('.pt', '.onnx')
    if os.path.exists(onnx_source):
        shutil.copy(onnx_source, f'{MODELS_DIR}/{release}.onnx')
        print(f"✓ .onnx → {MODELS_DIR}/{release}.onnx")
    else:
        print(f"✗ ONNX export not found at {onnx_source}")

    print(f"\nRelease : {release}")
    print(f"Classes : {len(CLASS_MAP)} ({', '.join(CLASS_MAP)})")
    print(f"Images  : {img_count}")