# -*- coding: utf-8 -*-
"""ShapeDetectorConvertor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQ01NjBybz7q4rrsd6p9V79zSdey7h1q
"""

import tensorflow as tf
import numpy as np
import json
import os
import shutil

model = tf.keras.models.load_model('shapedetector_model_4b.h5', compile=False)

augmentation_layer_types = (
    tf.keras.layers.RandomFlip,
    tf.keras.layers.RandomRotation,
    tf.keras.layers.RandomZoom,
    tf.keras.layers.RandomTranslation,
    tf.keras.layers.RandomContrast,
)

real_layers = [
    l for l in model.layers
    if not isinstance(l, augmentation_layer_types)
    and not (
        hasattr(l, 'layers')
        and all(isinstance(sl, augmentation_layer_types) for sl in l.layers)
    )
]

print("Keeping layers:")
for l in real_layers:
    print(f"  {l.name:30s}  {type(l).__name__}")

inference_model = tf.keras.Sequential(name="shape_detector")
inference_model.add(tf.keras.Input(shape=(28, 28, 3)))
for layer in real_layers:
    inference_model.add(layer)

inference_model.summary()

dummy = np.zeros((1, 28, 28, 3), dtype=np.float32)
output = inference_model.predict(dummy)
assert output.shape == (1, 4), f"Unexpected output shape: {output.shape}"
print(f"Output shape  : {output.shape}")
print(f"Output values : {output}")
print(f"Predicted class index: {np.argmax(output)}")

for path in ['savedmodel', 'tfjs_model_clean']:
    if os.path.exists(path):
        shutil.rmtree(path)

inference_model.export('savedmodel')

os.system(
    "tensorflowjs_converter "
    "--input_format=tf_saved_model "
    "--output_format=tfjs_graph_model "
    "savedmodel "
    "tfjs_model_clean"
)

os.system("zip -r tfjs_model_clean.zip tfjs_model_clean")

with open('tfjs_model_clean/model.json') as f:
    m = json.load(f)

print("\nmodel.json top-level keys:", list(m.keys()))
print("Format:", m.get('format', 'unknown'))
print("\nDone. Download tfjs_model_clean.zip")
